### ISSUE TITLE
'Donquixote Doflamingo, Plot to Destroy the World' missing picture

### ISSUE THREAD

**Issue by Travanoid** [RoboCafaz/TreasureGuide#58]
## Description
This unit (and it's un-evolved form) is missing a portrait, and displays the fall-back '?' icon.

## Notes
[The unit has a picture on OPTC-DB](http://optc-db.github.io/characters/#/view/2201), but it is not getting pulled over onto NakamaNetwork correctly.
This unit was Global-only for a bit, so it didn't initially have an image on OPTC-DB, maybe that is why the '?' icon is still displayed?
The un-evolved form of this unit (Unit ID 2200) also displays the '?' icon

## Screenshot
![image](https://user-images.githubusercontent.com/28797307/39414833-e8988dac-4bf0-11e8-9f8c-927c972767fe.png)

**Comment by RoboCafaz** [comment]
Fixed in commit 91366d664cdcd8b123ca58fd63672f7a14ba17f1, which will be deployed soonish.
